source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'YLBAwemeResource_Example' do
  pod 'YLBAwemeResource', :path => '../'
  #基础库
  pod 'YLBCommon', :git => 'https://github.com/ProBobo/YLBCommon.git'
  target 'YLBAwemeResource_Tests' do
    inherit! :search_paths

    
  end
end
